// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUtE9XSY4dKaUw1czevIV93RbuHfzRcy8',
    appId: '1:1012836256940:web:25611cd3a9fbb25c972309',
    messagingSenderId: '1012836256940',
    projectId: 'auth-demo-b12fa',
    authDomain: 'auth-demo-b12fa.firebaseapp.com',
    storageBucket: 'auth-demo-b12fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOBkTpwlGI9YmaZ4EblVNDFNVkflAn4CA',
    appId: '1:1012836256940:android:0b22b861b3987f7b972309',
    messagingSenderId: '1012836256940',
    projectId: 'auth-demo-b12fa',
    storageBucket: 'auth-demo-b12fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0wW70P8RHf_YziJEOxlfNc0flE3HbnE',
    appId: '1:1012836256940:ios:b668319e0439c495972309',
    messagingSenderId: '1012836256940',
    projectId: 'auth-demo-b12fa',
    storageBucket: 'auth-demo-b12fa.firebasestorage.app',
    iosBundleId: 'com.example.pf30AuthWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW0wW70P8RHf_YziJEOxlfNc0flE3HbnE',
    appId: '1:1012836256940:ios:b668319e0439c495972309',
    messagingSenderId: '1012836256940',
    projectId: 'auth-demo-b12fa',
    storageBucket: 'auth-demo-b12fa.firebasestorage.app',
    iosBundleId: 'com.example.pf30AuthWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUtE9XSY4dKaUw1czevIV93RbuHfzRcy8',
    appId: '1:1012836256940:web:2814418726a49a20972309',
    messagingSenderId: '1012836256940',
    projectId: 'auth-demo-b12fa',
    authDomain: 'auth-demo-b12fa.firebaseapp.com',
    storageBucket: 'auth-demo-b12fa.firebasestorage.app',
  );
}
