import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:pf_32_firestore_cloud_messaging/firebase_options.dart';
import 'package:pf_32_firestore_cloud_messaging/notification_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  // This uses the DefaultFirebaseOptions generated by the FlutterFire CLI.
  // If you are setting this up manually, you might not have this file yet.
  // The README explains how to generate it.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    // Initialize our custom notification service
    await NotificationService().initialize();
  } catch (e) {
    debugPrint("Firebase initialization failed: $e");
    debugPrint(
      "Make sure you have configured your Firebase project correctly.",
    );
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FCM Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'FCM Notification Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String? _fcmToken;
  String _lastMessage = "No notifications yet";

  @override
  void initState() {
    super.initState();
    _setupInteractedMessage();
    _getToken();

    // Listen to foreground messages to update UI
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      setState(() {
        _lastMessage =
            "Foreground Message:\nTitle: ${message.notification?.title}\nBody: ${message.notification?.body}";
      });
    });
  }

  Future<void> _getToken() async {
    String? token = await NotificationService().getToken();
    setState(() {
      _fcmToken = token;
    });
    debugPrint("FCM Token: $_fcmToken");
  }

  // It is assumed that all messages contain a data field with the key 'type'
  Future<void> _setupInteractedMessage() async {
    // Get any messages which caused the application to open from
    // a terminated state.
    RemoteMessage? initialMessage = await FirebaseMessaging.instance
        .getInitialMessage();

    if (initialMessage != null) {
      _handleMessage(initialMessage);
    }

    // Also handle any interaction when the app is in the background via a
    // Stream listener
    FirebaseMessaging.onMessageOpenedApp.listen(_handleMessage);
  }

  void _handleMessage(RemoteMessage message) {
    setState(() {
      _lastMessage =
          "Opened from Notification:\nTitle: ${message.notification?.title}\nBody: ${message.notification?.body}";
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text(
                'Last Notification:',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 10),
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.grey[200],
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: Colors.grey),
                ),
                child: Text(
                  _lastMessage,
                  textAlign: TextAlign.center,
                  style: const TextStyle(fontSize: 16),
                ),
              ),
              const SizedBox(height: 30),
              const Text(
                'FCM Token (Copy for Firebase Console):',
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 5),
              SelectableText(
                _fcmToken ?? "Fetching token...",
                textAlign: TextAlign.center,
                style: const TextStyle(color: Colors.blue),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
